// <auto-generated />
using System;
using CodeFirst.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20220505094113_AddedCFTables")]
    partial class AddedCFTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.Entities.Group", b =>
                {
                    b.Property<int>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdGroup")
                        .HasName("Group_pk");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("CodeFirst.Entities.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("IndexNumber")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("IdStudent")
                        .HasName("Student_pk");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("CodeFirst.Entities.StudentGroup", b =>
                {
                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 5, 5, 11, 41, 12, 849, DateTimeKind.Local).AddTicks(8914));

                    b.HasKey("IdGroup", "IdStudent")
                        .HasName("StudentGroup_pk");

                    b.HasIndex("IdStudent");

                    b.ToTable("Student_Group");
                });

            modelBuilder.Entity("CodeFirst.Entities.StudentGroup", b =>
                {
                    b.HasOne("CodeFirst.Entities.Group", "IdGroupNavigation")
                        .WithMany("StudentGroups")
                        .HasForeignKey("IdGroup")
                        .HasConstraintName("StudentGroup_Group")
                        .IsRequired();

                    b.HasOne("CodeFirst.Entities.Student", "IdStudentNavigation")
                        .WithMany("StudentGroups")
                        .HasForeignKey("IdStudent")
                        .HasConstraintName("StudentGroup_Student")
                        .IsRequired();

                    b.Navigation("IdGroupNavigation");

                    b.Navigation("IdStudentNavigation");
                });

            modelBuilder.Entity("CodeFirst.Entities.Group", b =>
                {
                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("CodeFirst.Entities.Student", b =>
                {
                    b.Navigation("StudentGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
